name: Releases

on:
  release:
    types:
      - published

jobs:
  update-major-version-tag:
    permissions:
      contents: write
    uses: ./.github/workflows/reusable.yaml
    with:
      release_tag: ${{ github.event.release.tag_name }}
